config/routes.rb
Rails.application.routes.draw do
  root "user_details#index"
  get "/user_details/log_in", to: "user_details#log_in"
  post "/user_details/log_in", to: "user_details#sign_in"
  resources :user_details
  resources :tweets



  # get 'tweet/index'
  # get 'tweet/create'
  # get 'tweet/new'
  # get 'tweet/destroy'
  # get 'tweet/delete'
  # get 'tweet/edit'
  # get 'tweet/update'
  # get 'tweet/show'

  #POST request is automatically mapped to CREATE action.
  #PATCH/PUT request is automatically mapped to UPDATE action.

 


  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/tweet.rb
class Tweet < ApplicationRecord
	validates :user_name, :content, presence: true # need to add user_detail_id
	#belongs_to :user_detail
end

app/models/user_detail.rb
class UserDetail < ApplicationRecord
  validates :first_name, :last_name, :user_name, :password, presence: true #need to add :tweet_id
  has_many :tweet
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  def index
  	@tweets = Tweet.all
  end

  def show
  	@tweet = Tweet.find(params[:id])
  end

  def destroy
		@tweet = Tweet.find(params[:id])
    @tweet.destroy

    redirect_to tweets_path, status: 303
  end

  def delete
  end

  def create
  	@tweet = Tweet.new(tweet_params)
  	# debugger
    if @tweet.save
      redirect_to @tweet
    else
      render :new, status: 422
    end
  end

  def new
  	@tweet = Tweet.new
  end

  def edit
  	@tweet = Tweet.find(params[:id])
  end

  def update
  	@tweet = Tweet.find(params[:id])

    if @tweet.update(tweet_params)
      redirect_to @tweet
    else
      render :edit, status: 422
    end
  end

  private

  def tweet_params
  	params.require(:tweet).permit(:user_name, :content)
  end
end

app/controllers/user_details_controller.rb
class UserDetailsController < ApplicationController

  def create
    @user = UserDetail.new(user_d_params)
    if @user.save 
      redirect_to @user
    else
      redirect_to new_user_detail
    end
  end

  def index
 
  end

  def log_in
  end

  def new
    @user = UserDetail.new
  end

  def sign_in
    if UserDetail.find_by(user_name: params[:user_name]) && UserDetail.find_by(password: params[:password])
      redirect_to tweets_path
    else
      redirect_to root_path
    end
  end

  def show
    @user = UserDetail.find(params[:id])
  end

  

  private

  def user_d_params
    params.require(:user_detail).permit(:first_name, :last_name, :user_name, :passsword)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/user_details_helper.rb
module UserDetailsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Twitter</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tweets/delete.html.erb
<h1>Tweets#delete</h1>
<p>Find me in app/views/tweets/delete.html.erb</p>

app/views/tweets/destroy.html.erb
<h1>Tweets#destroy</h1>
<p>Find me in app/views/tweets/destroy.html.erb</p>

app/views/tweets/edit.html.erb
<%= form_with(model: @tweet )do |form| %>

  <%= "USERNAME:"%><br>
  <h4><%= @tweet.user_name%><h4><br>
  <%= form.label :content, "Edit Tweet:" %><br>
  <%= form.text_area :content, size: "50x5" %><br>

  <%= form.submit "Submit" %><br>
<% end %>
<li><%= link_to('Home', tweets_path) %></li>

app/views/tweets/index.html.erb
<h2>Welcome to Twitter</h2><br>
<%= "We have" %>
<%= @tweets.count %>
<%= "Tweets as of now." %><br>

<ul><% @tweets.each do |var| %><br>
  <li><%= var.user_name %></li><br>
  <%= var.content %><br>
<% end %> </ul>

<h3><%= link_to('Write Your New Tweet Here', "tweets/new") %></h3><br>

app/views/tweets/new.html.erb
<%= form_with(model: @tweet )do |form| %>

  <%= form.label :user_name, "Enter Your User Name" %><br>
  <%= form.text_field :user_name %><br>

  <%= form.label :content, "Your Tweet Goes Here:" %><br>
  <%= form.text_area :content, size: "50x5" %><br>

  <%= form.submit "Submit" %><br>
<% end %>
<li><%= link_to('Home', tweets_path) %></li>

app/views/tweets/show.html.erb
<%= "USERNAME:"%>
<h1><%= @tweet.user_name %></h1>
<%= "TWEET:"%>
<h4><%= @tweet.content %></h4>

<ul>
  <li><%= link_to "Edit", edit_tweet_path(@tweet) %></li>
  <li><%= link_to "Delete", tweet_path(@tweet), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li>
  <li><%= link_to('Home', tweets_path) %></li>
</ul>

app/views/tweets/update.html.erb
<h1>Tweets#update</h1>
<p>Find me in app/views/tweets/update.html.erb</p>

app/views/user_details/index.html.erb
<h2>Welcome to Twitter</h2><br>

If you are new here then 
<%= link_to('Sign Up', "/user_details/new") %><br>
<%= "OR ELSE "%>
<%= link_to('Login', "/user_details/log_in") %><br>

app/views/user_details/log_in.html.erb
<h3>Login Form</h3>
<%= form_with model: @user do |form| %>
  <%= form.label :user_name, "Enter Your User Name:" %><br>
  <%= form.text_field :user_name %><br>

  Enter Your Password:<br>
  <%= form.password_field :password %><br>

  <%= form.submit "Submit" %><br>
<%end%>

app/views/user_details/new.html.erb
<%= form_with model: @user do |form| %>

  <%= form.label :first_name, "Enter Your First Name" %><br>
  <%= form.text_field :first_name %><br>

  <%= form.label :last_name, "Enter Your Last Name" %><br>
  <%= form.text_field :last_name %><br>

  <%= form.label :user_name, "Enter Your User Name" %><br>
  <%= form.text_field :user_name %><br>

  Password:<br>
  <%= form.password_field :password %><br>

  <%= form.submit "Submit" %><br>
<% end %>

app/views/user_details/show.html.erb
First Name:
<%= @user.first_name %><br>
Last Name:
<%= @user.last_name %><br>
Username:
<%= @user.user_name %><br>

<%= link_to('New User', user_details_path) %><br>
<%= link_to('Twitter Home Page', tweets_path) %><br>